services:
  web:
    build: .
    container_name: apache2
    restart: unless-stopped
    ports:
      - "7021:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - PHP_MEMORY_LIMIT=256M
      - PHP_UPLOAD_MAX_FILESIZE=50M
    networks:
      - app-network

networks:
  app-network:
    driver: bridge